### PR TITLE
Make this a Distribution for 6.1

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
In Plone 6.1 I would not let this package depend on `Products.CMFPlone`, but the other way around.  I have updated https://github.com/plone/Products.CMFPlone/issues/3953 with some thoughts.  But we could decide differently.

Also, I would not move to native namespaces at this point.  I still think this is best done for all packages in Plone 7.

**Comment by jensens** [comment]
Well, I do not think we should start with the wrong direction. 

-> I think we should first start with a distribution here and then make first a plan and then move templates over here.

**Comment by mauritsvanrees** [comment]
I fixed a few problems on [a branch](https://github.com/plone/plone.classicui/tree/maurits-distribution-pyproject-toml).  But moving this to pyproject.toml-only is not possible yet, unfortunately: it does not work with Buildout in development mode: https://github.com/buildout/buildout/issues/652

And just to reiterate my point on moving to native namespaces: I am against that in Plone 6.  Theoretically we could do this, but then we need to do this for all packages in the plone namespace.  Otherwise if someone wants to fix a bug in another package that still uses pkg_resources-namespaces, they must first move that package to native namespaces, otherwise you cannot even install it in development mode together with already modernised packages.  I really don't want that hassle in Plone 6.x.

Closing this in favour of PR #9.

**Comment by jensens** [comment]
> And just to reiterate my point on moving to native namespaces: I am against that in Plone 6. Theoretically we could do this, but then we need to do this for all packages in the plone namespace. Otherwise if someone wants to fix a bug in another package that still uses pkg_resources-namespaces, they must first move that package to native namespaces, otherwise you cannot even install it in development mode together with already modernised packages. I really don't want that hassle in Plone 6.x.

FTR: Using `pyproject.toml` (and dropping setup.*) is not related to using native namespaces, these topics are completely unrelated.

**Pull request closed without merging**
